### ISSUE TITLE
Similar library

### ISSUE THREAD

**Issue by pocesar** [jonschlinkert/set-value#1]
There's already another similar library called `object-path`, just FYI

**Comment by jonschlinkert** [comment]
1. this library is focused on doing one thing well
2. this handles escaping for dot notation, which is a requirement if object keys are ever things like file paths, which would happen in any build system like gulp or grunt, or with templates, or with file paths in express, and so on. 
3. this was created months ago but was renamed today from https://github.com/jonschlinkert/set-object, to be consistent with https://github.com/jonschlinkert/has-value and https://github.com/jonschlinkert/get-value. 
4. that lib fails 50% of the tests in this library, none of which I would consider edge cases:

![screen shot 2015-03-25 at 3 39 06 pm](https://cloud.githubusercontent.com/assets/383994/6833658/1caa3356-d305-11e4-9958-fb25495ddf5f.png)

Please do more research and have something to back up your words before you waste someone's time like this.
