### ISSUE TITLE
Dependency on is-plain-object

### ISSUE THREAD

**Issue by EJBroeders** [jonschlinkert/set-value#10]
Would it make sense to replace the dependency on is-plain-object with:
``const isPlain = obj => typeof obj === 'object';`` ?

This would reduce the total number of dependencies to zero, which is always a great aim on itself.

**Comment by jonschlinkert** [comment]
No, that's not the same thing. That would return true for `null`, an instance of `Date`, `RegExp`,  `Map`, `Set` or any other native or custom constructor. A plain object is specifically an object that was created by the `Object` constructor.
