### ISSUE TITLE
Quarantine set-value@2.0.1

### ISSUE THREAD

**Issue by PoojaWali** [jonschlinkert/set-value#15]
Hi ,

I am facing 

18186 verbose stack Error: 403 Requested item is quarantined: set-value@http://nexus/repository/npmpublic/set-value/-/set-value-2.0.1.tgz ..

I am using angular :^6.0.1 and i have explicitly added set-value:^3.0.1.! After npm install i am facing same issue again

**Comment by doowb** [comment]
This looks like it's an issue with npm or whatever `nexus` is. `set-value@2.0.1` is a patched version and does not have a vulnerability.

**Comment by millette** [comment]
@doowb Could you publish the 2.0.1 tag (release) to github? It seems to be missing (but published to npm, where it matters).

**Comment by doowb** [comment]
I'll update the tags later tonight.

**Comment by doowb** [comment]
2.0.1 has been tagged.
