### ISSUE TITLE
Patch versions for older majors?

### ISSUE THREAD

**Issue by aaronjensen** [jonschlinkert/set-value#16]
Hi there, any chance of releasing patch versions with the security fix for the older major versions? Many very popular libraries depend on `^2.0.0` or even `0.X`. Thanks!

**Comment by heyimalex** [comment]
Just for reference, [here's the advisory](https://www.npmjs.com/advisories/1012). I saw another [comment](https://github.com/jonschlinkert/set-value/issues/15#issuecomment-508945135) that said it'd also been patched in the 2.0.1 patch, maybe the advisory should be changed to reflect that.

**Comment by etisdew** [comment]
the only way to watch this right now is by commenting, so I am commenting

**Comment by aaronjensen** [comment]
> the only way to watch this right now is by commenting, so I am commenting

This works too:

![CleanShot 2019-07-12 at 13 43 28](https://user-images.githubusercontent.com/8588/61157458-0e6e8e00-a4ab-11e9-941f-70a9fbd79ca0.png)

**Comment by chaosZeroFive** [comment]
Unfortunately a ton of bundled modules under a ton of other modules reference v2...what is the fix?

**Comment by aaronjensen** [comment]
@chaosZeroFive it sounds like 2.0.1 has the fix, but the advisory doesn't know it yet, so npm audit doesn't know it yet.

**Comment by heyimalex** [comment]
Yeah, it's definitely applied in the 2.0.1 branch. I shot an email to npm support about this, hopefully they change the criteria for the advisory.

**Comment by heyimalex** [comment]
I was just emailed back by npm, they added 2.0.1 to remediated!

**Comment by doowb** [comment]
> I was just emailed back by npm, they added 2.0.1 to remediated!

I just verified that by running `npm audit` on the same package I did before, this now returns 0 vulnerabilities.

**Comment by philmayfield** [comment]
Greatly appreciate the fix.  Just a heads up that this still shows as vulnerable in the Github Advisory Database.

[https://github.com/advisories/GHSA-4jqc-8m5r-9rpr](https://github.com/advisories/GHSA-4jqc-8m5r-9rpr)
