### ISSUE TITLE
proposal (breaking change)

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/set-value#3]
What you think about to force `set-value` to only create values if they not exists in object?
And we can use [tunnckoCore/put-value(s)](https://github.com/tunnckoCore/put-value) to only update values if they exist in the given object.

I've also created `del-value` (which also works as reset for deletion and will push up in a bit `put-values` and `del-values`

***
### [tunnckoCore/del-value](https://github.com/tunnckoCore/del-value) - `del(obj, key)`
- if `key` not string or array returns original `obj`
- if `obj` is not an object return empty object

### [tunnckoCore/del-values](https://github.com/tunnckoCore/del-values) - `del(obj, key)`
- where `key` can be array of dot notation paths

### [tunnckoCore/put-value](https://github.com/tunnckoCore/put-value) - `put(obj, key, value)`
- updates value of `key` only if `key` exists
- updates only existing values of `obj` when object is given to `key` (like `assign-deep`)
- because `set-value` **update** values if exist and **add** if not exist
- returns original object if `key` is not an object or string
- returns empty object if `obj` is not an object
- returns modified object otherwise

### [tunnckoCore/put-values](https://github.com/tunnckoCore/put-values) - `put(obj, key, value)`
- where `key` can be array of dot notation paths, as seen in `del-value` for now

### set-value proposal - `set(obj, key, value)`
- sets `value` only if it not exist in `obj`
- if `key` is object, extend `obj` without overwriting existing values (like `defaults-deep`)

***

And all that because im writing [tunnckoCore/store-cache](https://github.com/tunnckoCore/store-cache) (i'll push up in a bit) in which i want to have different methods for different behaviors - store, set, get, put, del, has. At the moment it mostly looks like `option-cache` but with different idea and behaviors.

**Comment by jonschlinkert** [comment]
> to only create values if they not exists in object?

@doowb and I have talked about this, I'm really not sure. Let me think about it

**Comment by jonschlinkert** [comment]
actually I have an idea... give me a minute

**Comment by doowb** [comment]
Would `set-value` throw an error if attempting to set an existing value?
Should it return the existing value?

I understand the use case when it comes to RESTful apis and using the proper verbs for the situation, but is this something that's needed for setting a value on a javascript object?

It might be useful, but I can see people getting unexpected results if there's no notification when it fails to set an existing value.

2¢

**Comment by jonschlinkert** [comment]
okay, so in addition to the libs you created, @tunnckoCore do you want to create either `default-value` or `fillin-value`? (both `fillin` and `defaults` are used for extending an object without overwriting existing values).

I'll do `omit-value`, `assign-value`, where `omit-value` is like `del-value` but does a shallow clone of the object, and `assign-value` extends an existing object. Then I can remove some functionality from `set-value` and require `assign-value` back in. We can use `omit-value` and `default-value` as well. 

sound good? @doowb?

**Comment by tunnckoCore** [comment]
> Would set-value throw an error if attempting to set an existing value?
Should it return the existing value?

nope, won't throw and always should return this

@jonschlinkert that names. lol. Actually i realize these days that neither of your extending/merge utils didn't work like i think and either do 99.9% same thing. Talkin' about `extend-shallow`, merge-deep, assign-deep, defaults-deep and mixin-deep - tried  so much tests.

> I'll do omit-value, assign-value, where omit-value is like del-value but does a shallow clone of the object,

you can PR to del-value, i also want that.

**Comment by doowb** [comment]
I think these can be useful. I think there should be a library that will always set the value (`upsert-value`, `pset-value`).

**Comment by tunnckoCore** [comment]
example

```js
function update (o) {
  if (!isPlainObject(o)) {
    return {}
  }

  var len = arguments.length
  var i = 1

  while (i < len) {
    var arg = arguments[i++]
    objectEach(o, function (key, val) {
      if (hasOwn.call(arg, key)) {
        o[key] = arg[key]
      }
    })
  }

  return o
}


var obj = {a: {b: 'bbb'}}
console.log(update(obj, {a: {b: 123}}))    //=> {a: {b: 123}}
// console.log(update(obj, {a: {z: 'zzz'}}))  //=> {a: {z: 'zzz'}}

// console.log(update(obj, {z: 'zzz'}))       //=> {a: {b: 'bbb'}}
// console.log(update(obj, {z: {z: 123}}))    //=> {a: {b: 'bbb'}}

// console.log(update(obj, {a: 'abc'}, {a: 777}))    //=> {a: 777}
// console.log(update(obj, {a: 'abc'}, {z: 'zzz'}))  //=> {a: 'abc'}
// console.log(update(obj, {z: 'zzz'}, {a: 123}))    //=> {a: 123}
```

**Comment by tunnckoCore** [comment]
> I think there should be a library that will always set the value

agreed and realize that, after i opened this issue

**Comment by jonschlinkert** [comment]
- https://github.com/jonschlinkert/assign-value
- https://github.com/jonschlinkert/omit-value

> you can PR to del-value, i also want that.

why? I'd rather use `del-value` without having to shallow clone when I don't need a shallow clone... usually I want to keep a reference to the original object

**Comment by jonschlinkert** [comment]
> i think and either do 99.9% same thing

they don't though. "merging" usually implies "deep" merging, which also often includes deep cloning the values. "extend" and "assign" are the same. They are like `merge` but are usually shallow clones and done extend any nested properties. Additionally, `extend` usually only extends `own` properties, but not always. `mixin` is similar but does not typically check if a property is an `own` property and doesn't do any cloning, and it is usually used for adding properties from object `B` with function values to object `A`.

**Comment by jonschlinkert** [comment]
`update-value` or `upsert-value` sound useful too. whoever wants to do those...

**Comment by jonschlinkert** [comment]
@tunnckoCore when did you stop adding semicolons? I think I'll stop adding punctuation to all of my sentences lol

**Comment by tunnckoCore** [comment]
and what should do `update-value`? for that is `put-value`? in terms of REST it means update.

And note about object checking in `assing-value` and omit-value, i dont think it should use `is-extendable`.

**Comment by jonschlinkert** [comment]
> i dont think it should use is-extendable.

curious why? shouldn't functions be extendable too?

**Comment by tunnckoCore** [comment]
no, just cant see the case that you would want to set/put/del and etc to RegExp, Array and etc.
So im thinking that we should limit it only to object and functions.

**Comment by jonschlinkert** [comment]
> isobject is enough.

doesn't `isobject` return false for functions?

**Comment by jonschlinkert** [comment]
sorry I can look in a minute...

**Comment by tunnckoCore** [comment]
> doesn't isobject return false for functions?

actually yea, my fault. so typeof fn + isobject.

**Comment by jonschlinkert** [comment]
> so typeof fn + isobject.

or `is-extendable` :)

**Comment by jonschlinkert** [comment]
btw, have you ever tried doing this? (not that there are many idiomatic use cases for these):

```js
var arr = ['foo', 'bar'];
arr.baz = 'quux';
console.log(arr);
console.log(arr.length);
console.log(arr.baz);
```
or regex:
```js
var re = /foo/;
foo.bar = 'baz';
console.log(foo);
console.log(foo.bar);
```

**Comment by tunnckoCore** [comment]
> or is-extendable :)

doh im not okey, srsly ;d

> btw, have you ever tried doing this?

yep, exactly what im talking about. but okey nevermind it's okey.

**Comment by tunnckoCore** [comment]
mm @jonschlinkert, want to merge them in one org?

`set-value`
`get-value`
`del-value`
`has-value`
`has-own-deep`
`has-any` * im not sure
`object.omit`
`upsert-value`
`put-value`
`assign-value`
`omit-value`

**Comment by jonschlinkert** [comment]
no, I'd rather keep as-is. thanks though

**Comment by jonschlinkert** [comment]
closing based on prev comment
