### ISSUE TITLE
Any plan to support array?

### ISSUE THREAD

**Issue by leesei** [jonschlinkert/set-value#6]
<strike>`get-value` supports `get(obj, 'e[0].f')`</strike>. See https://github.com/jonschlinkert/get-value/issues/4
But `set-value` does not create an array given `set(obj, 'e[0].f', 'g')`.
It returns `{ 'e[0]': { f: 'g' } }`.

**Comment by jonschlinkert** [comment]
This would probably be pretty easy to do. I'll add it as a feature request and look into it next time I make changes.

**Comment by jonschlinkert** [comment]
Closing since arrays are already supported. Instead of doing `a.[0].b` you can just do `a.0.b`

**Comment by jmtoball** [comment]
Just a note: For me it was unexpected that while set-value supports pushing values to existing arrays, the same path will result in an object being created if no array exists yet at the key. I understand the ambiguity here, but the decision to default to array-creation for index keys as 'lodash.set' felt more intuitive to me.
